apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-acg
  region: il-central-1
  version: "1.20"

vpc:
  cidr: 10.0.0.0/16

nodeGroups:
  - name: eks-node-group-v2
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: true
